{% set name = "qiskit-machine-learning" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-machine-learning-{{ version }}.tar.gz
  sha256: c332e9d3ea658b2d24b401e5264b239f1093378952a70ba46c73a69a3ce7c727

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=40.1.0
  run:
    - dill >=0.3.4,<0.3.6
    - fastdtw
    - numpy >=1.17
    - psutil >=5
    - python >=3.7
    - qiskit-terra >=0.22
    - scikit-learn >=0.20.0
    - scipy >=1.4
    - setuptools >=40.1.0

test:
  imports:
    - qiskit_machine_learning
    - qiskit_machine_learning.algorithms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/qiskit-machine-learning
  summary: 'Qiskit Machine Learning: A library of quantum computing machine learning experiments'
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
